spring:
  data:
    mongodb:
     uri: mongodb://localhost:27017
     database: ecommerce

logging:
  level:
    org.springframework.web:  DEBUG
    #org.springframework.data.mongodb.core.MongoTemplate: DEBUG
server:
  port: 8081
